const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');

const source = fs.readFileSync('app/static/app.js', 'utf8');

const utilitySource = source.slice(0, source.indexOf('function toast('));
const context = { window: { crypto: undefined }, localStorage: { getItem: () => null }, location: { hash: '' }, Uint8Array, Math, Blob, File, URL };
vm.runInNewContext(`${utilitySource}; this.createUuidForTest = createUuid; this.navigateForTest = navigateToServiceRequest; this.normalizePhotoForTest = normalizeDraftPhoto;`, context);
const fallbackUuid = context.createUuidForTest();
assert.match(fallbackUuid, /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
context.navigateForTest('request-123');
assert.equal(context.location.hash, 'requests/request-123');
const restoredPhoto = context.normalizePhotoForTest({ blob: new Blob(['photo'], { type: 'image/jpeg' }), name: 'restored.jpg', type: 'image/jpeg' });
assert.ok(restoredPhoto.file instanceof File, 'restored IndexedDB blob must be normalized to File');
assert.equal(restoredPhoto.file.name, 'restored.jpg');

const mapping = source.match(/const statusAction = (\{[^;]+\});/);
const actionBlock = source.match(/const nextAction = statusAction\[request\.status\];[\s\S]*?: '';/);
assert.ok(mapping && actionBlock, 'Technician action renderer must be present');
const renderAction = new Function('status', 'completionQueued', 'completionSync', `const statusAction = ${mapping[1]}; ${actionBlock[0].replaceAll('request.status', 'status')} return action;`);
const noPendingPhotos = { photos: [] };
const synced = { fullySynced: true };
const pendingPhotos = { fullySynced: false };
assert.match(renderAction('assigned', false, synced), /data-status="on_the_way"[^>]*>Выехал/);
assert.match(renderAction('on_the_way', false, synced), /data-status="in_progress"[^>]*>Начать работу/);
assert.match(renderAction('arrived', false, synced), /data-status="in_progress"[^>]*>Начать работу/);
assert.match(renderAction('in_progress', false, synced), /Завершить работу/);
assert.match(renderAction('in_progress', true, pendingPhotos), /Повторить синхронизацию/);
assert.match(renderAction('waiting_parts', false, synced), /Продолжить работу/);
assert.equal(renderAction('waiting_approval', false, synced), '');
assert.equal(renderAction('completed', false, synced), '');
assert.match(renderAction('completed', true, pendingPhotos), /Повторить отправку фото/);

assert.match(source, /const draft = \{ diagnostic: '', work: '', comment: '', usedParts: \{\}, photos: \[\] \}/);
assert.match(source, /URL\.createObjectURL\(file\)/);
assert.match(source, /URL\.revokeObjectURL\(photo\.url\)/);
assert.match(source, /completionLocalUuid \|\|= window\.FixitOffline\?\.uuid\?\.\(\) \|\| createUuid\(\)/);
assert.doesNotMatch(source, /on_the_way: \['arrived'/);
assert.match(source, /Ожидается согласование/);
assert.match(source, /approval: \{ diagnostic: draft\.diagnostic/);
assert.match(source, /\/approval`, \{ method: 'PATCH'/);
assert.match(source, /const \[route, routeId, routeTab, routeChildId\] = hashRoute\.split\('\/'\)/);
assert.match(source, /state\.route === 'requests' && state\.requestId/);
assert.match(source, /RequestDraftStore\.put/);
assert.match(source, /window\.addEventListener\('pagehide', persistOnBackground\)/);
assert.match(source, /navigator\.mediaDevices\?\.getUserMedia/);
assert.match(source, /facingMode: \{ ideal: 'environment' \}/);
const technicianWorkspaceStart = source.indexOf('async function openTechnicianRequestWorkspace');
const technicianWorkspaceEnd = source.indexOf('// ============================================================\n// Раздел: Fixit Pulse', technicianWorkspaceStart);
const technicianWorkspaceSource = source.slice(technicianWorkspaceStart, technicianWorkspaceEnd);
assert.match(technicianWorkspaceSource, /capture="environment"/);
assert.match(technicianWorkspaceSource, /form\.append\('kind', 'approval'\)/);
assert.match(technicianWorkspaceSource, /\/service-requests\/\$\{request\.id\}\/attachments/);
assert.match(technicianWorkspaceSource, /photo\.approvalAttachmentId = attachment\.id/);
assert.ok(source.includes('data-request-photo'), 'Dispatcher request detail must render request photo thumbnails');
assert.match(source, /completionRepairId = persistedDraft\?\.completionRepairId \|\| null/);
assert.match(source, /FixitOffline\.enqueueRepair\(payload, draft\.photos/);
assert.match(source, /id="request-retry-sync"/);
assert.match(source, /Работа завершена · \$\{completionSync\.attachmentsPending\} фото ожидают отправки/);
assert.match(source, /FixitOffline\?\.configure\?\.\(\{ token: state\.token \}\)/);
assert.match(source, /FixitOffline\?\.db\?\.kvDelete\?\.\('token'\)/);
assert.match(source, /Фото оборудования/);
assert.match(source, /equipment-history-photos/);
const techSource = fs.readFileSync('app/static-tech/app.js', 'utf8');
const workerSource = fs.readFileSync('app/static-tech/sw.js', 'utf8');
assert.doesNotMatch(techSource, /if \(!pending\.length\) return resultsById/);
assert.match(techSource, /attachment\.file instanceof Blob/);
assert.match(workerSource, /await syncPendingAttachmentsFromSW\(token\)/);
assert.match(workerSource, /await self\.TechDB\.delete\('pendingAttachments', attachment\.id\)/);
console.log('technician workflow runtime: ok');
